- name: Déployer l'application sur la VM Google Cloud
  hosts: servers
  become: true
  tasks:
    - name: Update and upgrade
      apt:
        update_cache: yes
        upgrade: dist
    - name: Installer les dépendances
      apt:
        name:
          - git
          - make
        state: present

    - name: Install docker
      tags: install_docker
      shell: |
        sudo apt-get update
        for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg -y; done
        sudo apt-get install -y ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

    - name: Cloner le dépôt Git
      git:
        repo: "https://github.com/scelios/inception.git"
        dest: "/home/{{ ansible_user }}/inception"
        version: "main"

    - name: Copy .env to the git
      copy:
        src: "{{ env }}"
        dest: "/home/{{ ansible_user }}/inception/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

    - name: Exécuter `make init`
      command:
        chdir: "/home/{{ ansible_user }}/inception"
        cmd: "make init"

    - name: Exécuter `make up`
      command:
        chdir: "/home/{{ ansible_user }}/inception"
        cmd: "make up"