services:
  mysql:
    image: mysql:latest
    container_name: mysql_cloud
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cloud
      MYSQL_DATABASE: cloud_db
      MYSQL_USER: cloud_user
      MYSQL_PASSWORD: cloud1
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cloud_network
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:latest
    container_name: wordpress_cloud
    restart: always
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: cloud_user
      WORDPRESS_DB_PASSWORD: cloud1
      WORDPRESS_DB_NAME: cloud_db
      WORDPRESS_CONFIG_EXTRA: |
        define('FORCE_SSL_ADMIN', true);
        if (isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && $$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
          $$_SERVER['HTTPS'] = 'on';
        }
        if (isset($$_SERVER['HTTP_X_FORWARDED_HOST'])) {
          $$_SERVER['HTTP_HOST'] = $$_SERVER['HTTP_X_FORWARDED_HOST'];
        }
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - cloud_network
    ports:
      - "8080:80"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_cloud
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: cloud_user
      PMA_PASSWORD: cloud1
      MYSQL_ROOT_PASSWORD: cloud
    networks:
      - cloud_network
    ports:
      - "8081:80"
  
  nginx:
    image: nginx:alpine
    container_name: nginx_cloud
    restart: always
    depends_on:
      - wordpress
      - phpmyadmin
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/auth:/etc/nginx/auth:ro
    networks:
      - cloud_network
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"

volumes:
  mysql_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  cloud_network:
    driver: bridge