- name: Copy docker
  tags: launch
  copy:
    src: "{{ docker }}"
    dest: "/home/{{ ansible_user }}/inception"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Remove all Docker containers
  tags: launch
  shell: |
    if [ "$(docker ps -aq)" != "" ]; then
      docker rm -f $(docker ps -aq);
    fi

- name: Launch docker
  tags: launch
  command:
    chdir: "/home/{{ ansible_user }}/inception/docker"
    cmd: "docker compose up -d"